stages:
  - build

variables:
  CONTAINER_REGISTRY: eastus2tgacr.azurecr.io

image: docker:18.09.7
services:
- docker:18.09.7-dind

build:
  stage: build
  script:
    - docker login $CONTAINER_REGISTRY -u $SERVICE_USER -p $SERVICE_USER_PWD
    - docker build -t $CONTAINER_REGISTRY/apicirunner .
    - docker push $CONTAINER_REGISTRY/apicirunner
  only:
    - master